# Generated by Django 5.2 on 2025-04-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "capacidade",
                    models.FloatField(help_text="Capacidade total em litros"),
                ),
                ("nivel_atual", models.FloatField(help_text="Nível atual em litros")),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
