# Generated by Django 5.2 on 2025-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservatorio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservatorio",
            name="capacidade",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reservatorio",
            name="nivel_atual",
            field=models.FloatField(),
        ),
    ]
