# Generated by Django 5.2 on 2025-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservatorio", "0002_alter_reservatorio_capacidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservatorio",
            name="status_bomba",
            field=models.CharField(
                choices=[
                    ("Ligada", "Ligada"),
                    ("Desligada", "Desligada"),
                    ("Quebrada", "Quebrada"),
                ],
                default="Desligada",
                max_length=20,
            ),
        ),
    ]
