# Generated by Django 5.2 on 2025-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservatorio", "0003_reservatorio_status_bomba"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservatorio",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude do reservatório", null=True
            ),
        ),
        migrations.AddField(
            model_name="reservatorio",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude do reservatório", null=True
            ),
        ),
    ]
