# Generated by Django 5.2 on 2025-04-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservatorio", "0004_reservatorio_latitude_reservatorio_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservatorio",
            name="endereco",
            field=models.CharField(
                blank=True,
                help_text="Buscar endereço do reservatório",
                max_length=255,
                null=True,
            ),
        ),
    ]
