# Generated by Django 5.2 on 2025-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservatorio", "0005_reservatorio_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservatorio",
            name="endereco",
            field=models.CharField(
                blank=True,
                help_text="Endereço do reservatório",
                max_length=255,
                null=True,
            ),
        ),
    ]
