# Generated by Django 5.2 on 2025-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservatorio", "0006_alter_reservatorio_endereco"),
    ]

    operations = [
            migrations.CreateModel(
            name="Reservoir",
            fields=[]
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.FloatField()),
                ("current_level", models.FloatField()),
                
                    "pump_status",
                    models.CharField(
                        choices=[
                            ("On", "Ligada"),
                            ("Off", "Desligada"),
                            ("Broken", "Quebrada"),
                        ],
                        default="Off",
                        max_length=20,
                    ),]
        
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="Reservoir latitude", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="Reservoir longitude", null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Reservoir address",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Reservatorio",
        ),
    ]
